name: remove-retractions-from-esgf-world-catalog

on:
  push:
    branches:
      - 'create-catalog'
env:
    AWS_REGION: us-east-2
jobs:
  auth-filter-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: >
          $CONDA/bin/conda env update --file CatalogBuilder/environment_intake.yml --name base
      - id: 'generate catalog'
        run: python CatalogBuilder/gen_intake_s3.py
   
